services:
  mongo-testing:
    image: mongo:latest
    container_name: llm-twin-mongo-testing
    logging:
      options:
        max-size: 1g
    environment:
      MONGO_INITDB_ROOT_USERNAME: "test_user"
      MONGO_INITDB_ROOT_PASSWORD: "test_password"
      MONGO_INITDB_DATABASE: "llm-twin-test"
    # Use a port that doesn't clash with the application containers.
    ports:
      - 27018:27017
    volumes:
      - mongo_data_testing:/data/db
    networks:
      - local-testing
    restart: always

  qdrant-testing:
    image: qdrant/qdrant:latest
    container_name: llm-twin-qdrant-testing
    # Use ports that don't clash with the application containers.
    ports:
      - 6335:6333
      - 6336:6334
    expose:
      - 6335
      - 6336
    volumes:
      - qdrant_data_testing:/qdrant/storage
    networks:
      - local-testing
    restart: always

volumes:
  mongo_data_testing:
  qdrant_data_testing:

networks:
  local-testing:
    driver: bridge