name: Continuous integration

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27018:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: "test_user"
          MONGO_INITDB_ROOT_PASSWORD: "test_password"
          MONGO_INITDB_DATABASE: "llm-twin-test"

    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Pin to a specific uv version.
          version: "0.6.7"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Run mypy
        run: make mypy

      - name: Run ruff checker
        run: make check

      - name: Run import linter
        run: make lint_imports

      - name: Run unit tests
        run: make test_unit

      - name: Run integration tests
        run: make test_integration
